receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
connectors:
  spanmetrics:
    namespace: spanmetrics
processors:
  batch:
extensions:
  health_check: {}
exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    target_info:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,spanmetrics]
    metrics:
      receivers: [spanmetrics,otlp]
      processors: [batch]
      exporters: [prometheusremotewrite,prometheus]
